const fs=require('fs');
const {JSDOM}=require('jsdom');
const HTML=fs.readFileSync('index.html','utf8');
const dom=new JSDOM(HTML,{runScripts:'dangerously',url:'https://x.github.io/coach/'});
const w=dom.window;
const tick=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 await tick(150);
 const JSONB='{"objetivo":"forca","local":"quarto","exp":"pouco","dias":"4","tempo":"20","limit":"nenhum"}';
 const TEXTO='x ```plano\n'+JSONB+'\n``` y';
 const enc=encodeURIComponent(JSONB);
 const ev=(c)=>{try{return w.eval(c)}catch(e){return 'THROW: '+e.message}};
 console.log('tipo CZ:',ev('typeof CZ'));
 console.log('blocoDe:',JSON.stringify(ev('CZ.blocoDe('+JSON.stringify(TEXTO)+',"plano")')));
 console.log('validaPerfil:',ev('CZ.validaPerfil('+JSON.stringify(JSONB)+')'));
 console.log('perfilDoBloco(TEXTO):',ev('CZ.perfilDoBloco('+JSON.stringify(TEXTO)+',null)')?'ok':'null');
 console.log('perfilDoBloco(dec):',ev('CZ.perfilDoBloco(decodeURIComponent('+JSON.stringify(enc)+'),null)')?'ok':'null');
 console.log('JSON.parse direto:',ev('JSON.parse('+JSON.stringify(JSONB)+').dias'));
 console.log('PLANO_KEYS existe:',ev('!!CZ.PLANO_KEYS'));
 console.log('validaTimer existe:',ev('typeof CZ.validaTimer'));
})();
